version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"
  # Maintain dependencies for pom.xml
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Maven pom.xml"
      include: "scope"
  # Maintain dependencies from package.json
  - package-ecosystem: "npm"
    directory: "/src/main/webapp"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@patternfly/*"
        dependency-type: "direct"
      - dependency-name: "@cypress/*"
        dependency-type: "direct"
      - dependency-name: "cypress*"
        dependency-type: "direct"
