#
# Copyright 2019 Project OpenUBL, Inc. and/or its affiliates
# and other contributors as indicated by the @author tags.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: "3"

services:
  postgresql:
    image: postgres:13.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: searchpe_db
      POSTGRES_USER: db_username
      POSTGRES_PASSWORD: db_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_username -d searchpe_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/openubl-realm.json
      DB_VENDOR: h2
    volumes:
      - ./src/main/resources/openubl-realm.json:/tmp/openubl-realm.json:z
    command:
      - "-Djboss.bind.address.private=127.0.0.1"
      - "-Djboss.bind.address=0.0.0.0"
    network_mode: "host"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth" ]
      interval: 10s
      timeout: 5s
      retries: 5

  searchpe:
    image: quay.io/projectopenubl/searchpe:latest
    environment:
      QUARKUS_HTTP_PORT: 8180
      QUARKUS_DATASOURCE_USERNAME: db_username
      QUARKUS_DATASOURCE_PASSWORD: db_password
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/searchpe_db
      QUARKUS_OIDC_AUTH_SERVER_URL: http://localhost:8080/auth/realms/openubl
      QUARKUS_OIDC_CLIENT_ID: searchpe
      QUARKUS_OIDC_CREDENTIALS_SECRET: secret
      QUARKUS_PROFILE: "prod"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: "host"
    depends_on:
      postgresql:
        condition: service_healthy
      keycloak:
        condition: service_healthy
