---
kind: Service
apiVersion: v1
metadata:
  name: searchpe-db
  labels:
    app.kubernetes.io/name: searchpe-db
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: searchpe-db
    app.kubernetes.io/part-of: openubl-searchpe
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: searchpe-db
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: searchpe-db
  labels:
    app.kubernetes.io/name: searchpe-db
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: searchpe-db
    app.kubernetes.io/part-of: openubl-searchpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: searchpe-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: searchpe-db
    spec:
      volumes:
        - name: searchpe-db-data
          persistentVolumeClaim:
            claimName: searchpe-db
      containers:
        - name: postgres
          image: postgres:13.6
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "db_username"
            - name: POSTGRES_PASSWORD
              value: "db_password"
            - name: POSTGRES_DB
              value: "searchpe_db"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'psql -U $POSTGRES_USER -d $POSTGRES_DB -c ''SELECT 1'' '
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'psql -U $POSTGRES_USER -d $POSTGRES_DB -c ''SELECT 1'' '
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: searchpe-db-data
              mountPath: "/var/lib/postgresql"
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
