---
kind: Secret
apiVersion: v1
metadata:
  name: searchpe-db
stringData:
  USERNAME: username
  PASSWORD: password
  DATABASE: searchpe
  JDBC_URL: jdbc:postgresql://searchpe-db:5432/searchpe
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: searchpe-oidc
stringData:
  QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak/auth/realms/openubl
  QUARKUS_OIDC_CLIENT_ID: searchpe
  QUARKUS_OIDC_CREDENTIALS_SECRET: secret
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  name: searchpe-db
  labels:
    app.kubernetes.io/name: searchpe-db
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: searchpe-db
    app.kubernetes.io/part-of: openubl-searchpe
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: searchpe-db
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: searchpe-db
  labels:
    app.kubernetes.io/name: searchpe-db
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: searchpe-db
    app.kubernetes.io/part-of: openubl-searchpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: searchpe-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: searchpe-db
    spec:
      volumes:
        - name: searchpe-db-data
          persistentVolumeClaim:
            claimName: searchpe-db
      containers:
        - name: postgres
          image: postgres:13.7
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: USERNAME
                  name: searchpe-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PASSWORD
                  name: searchpe-db
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: DATABASE
                  name: searchpe-db
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
          livenessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'psql -U $POSTGRES_USER -d $POSTGRES_DB -c ''SELECT 1'' '
            initialDelaySeconds: 60
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - 'psql -U $POSTGRES_USER -d $POSTGRES_DB -c ''SELECT 1'' '
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: searchpe-db-data
              mountPath: "/var/lib/postgresql"
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
