apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: searchpe-catalog-source
  namespace: operators
spec:
  sourceType: grpc
  image: localhost:5000/searchpe-operator-catalog:test