apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: searchpe-catalog-source
  namespace: olm
spec:
  sourceType: grpc
  image: localhost:5000/searchpe-operator-catalog:0.0.0
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: openubl
spec:
  targetNamespaces:
    - openubl
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: searchpe-subscription
  namespace: openubl
spec:
  channel: alpha
  name: searchpe-operator
  source: searchpe-catalog-source
  sourceNamespace: olm
