---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "searchpe.fullname" . }}
  labels:
    {{- include "searchpe.labels" . | nindent 4 }}
stringData:
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.db.username }}
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.db.password }}
  QUARKUS_DATASOURCE_JDBC_URL: {{ .Values.db.jdbc_url }}
  QUARKUS_OIDC_AUTH_SERVER_URL: {{ .Values.oidc.auth_server_url }}
  QUARKUS_OIDC_CLIENT_ID: {{ .Values.oidc.client_id }}
  QUARKUS_OIDC_CREDENTIALS_SECRET: {{ .Values.oidc.credentials_secret }}
type: Opaque
