name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  jvm-tests:
    name: JVM Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Maven
        run: mvn test

  native-tests:
    name: Native Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ "standalone", "enterprise" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn verify -Dquarkus.native.container-build=true -P native,${{ matrix.flavor }}

  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        working-directory: src/main/webapp
        run: |
          npm install
          npm run build
      - name: Test
        working-directory: src/main/webapp
        run: npm run test -- --coverage --watchAll=false
      - uses: codecov/codecov-action@v3
        with:
          flags: unitests
