name: Container images generator

on:
  push:
    branches:
      - master

jobs:
  container-images:
    if: ${{ github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ "standalone", "enterprise" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Extract image name
        shell: bash
        run: |
          bash -c '
          flavor=${{ matrix.flavor }};
          image_name="searchpe";
          if [ $flavor != "standalone" ]; then
            image_name="$image_name-$flavor"
          fi
          echo $image_name;
          echo "##[set-output name=searchpe_image_name;]$(echo $image_name)"'
        id: extract_image_name

      - name: Build container image
        run: |
          mvn -U -B package --file pom.xml -DskipTests \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.registry=quay.io \
          -Dquarkus.container-image.group=projectopenubl \
          -Dquarkus.container-image.name=${{ steps.extract_image_name.outputs.searchpe_image_name }} \
          -Dquarkus.container-image.tag=early-access \
          -Dquarkus.container-image.username=${{ secrets.QUAYIO_USERNAME }} \
          -Dquarkus.container-image.password=${{ secrets.QUAYIO_PASSWORD }} \
          -P native,ui,${{ matrix.flavor }}
