name: Container images generator

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  container-images:
    if: ${{ github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ "standalone", "enterprise" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Build with Maven
        run: ./mvnw package -Dquarkus.native.container-build=true -DskipTests $MAVEN_ARGS
        env:
          MAVEN_ARGS: "-P ui,native,${{ matrix.flavor }}"
      - name: Extract image name
        shell: bash
        run: |
          bash -c '
          flavor="standalone";
          image_name="searchpe";
          if [ $flavor != "standalone" ]; then
            image_name="$image_name-$flavor"
          fi
          echo $image_name;
          echo "##[set-output name=searchpe_image_name;]$(echo $image_name)"'
        id: extract_image_name
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${{ matrix.flavor }})"
        id: extract_branch
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          registry: quay.io
          name: projectopenubl/${{ steps.extract_image_name.outputs.searchpe_image_name }}
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: src/main/docker/Dockerfile.native
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          registry: ghcr.io
          name: ${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ steps.extract_image_name.outputs.searchpe_image_name }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: src/main/docker/Dockerfile.native
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: projectopenubl/${{ steps.extract_image_name.outputs.searchpe_image_name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: src/main/docker/Dockerfile.native
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
