name: Container images generator

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  container-images:
    if: ${{ github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Build with Maven
        run: ./mvnw package -Pnative -Dquarkus.native.container-build=true -DskipTests
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          registry: quay.io
          name: projectopenubl/searchpe
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          dockerfile: src/main/docker/Dockerfile.native
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to GitHub Packages
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          registry: ghcr.io
          name: ${{ github.repository_owner }}/${{ github.event.repository.name }}/searchpe
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: src/main/docker/Dockerfile.native
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
      - name: Push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: projectopenubl/searchpe
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: src/main/docker/Dockerfile.native
          snapshot: false
          tags: ${{ steps.extract_branch.outputs.branch }}
