name: PR build container images

on: [push]

jobs:
  container-images:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner != 'project-openubl' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ "standalone", "enterprise" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build and Push to GitHub Packages
        run: |
          mvn package -DskipTests \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.name=${{ github.event.repository.name }}/searchpe-${{ matrix.flavor }} \
          -Dquarkus.container-image.tag=${{ steps.extract_branch.outputs.branch }} \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }} \
          $MAVEN_ARGS
        env:
          MAVEN_ARGS: "-P ui,native,${{ matrix.flavor }}"
