name: PR build container images comment by boot
on: pull_request

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up token
        id: token
        # This is a base64-encoded OAuth token for the "project-openubl-preview-bot" GitHub account, which has no secure access.
        run: echo "::set-output name=GH_TOKEN::`echo 'Z2hwX0RqQ0hpdUt2RFA2NmpiZlNlTkVLaFUzQVhST2R5YjNNbFIxeAo=' | base64 -d`"
      - name: Post Container image as PR comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            🚀 Container image Preview: `ghcr.io/${{github.event.pull_request.head.repo.full_name}}/${{github.event.repository.name}}:${{github.event.pull_request.head.ref}}` ✨
            - [Workflow runs](https://github.com/${{github.event.pull_request.head.repo.full_name}}/actions/workflows/pr-build-container-images.yml?query=branch%3A${{github.event.pull_request.head.ref}})
            - [Packages](https://github.com/${{github.event.pull_request.head.repo.full_name}}/packages)
          repo-token: ${{ steps.token.outputs.GH_TOKEN }}
