name: PR build container images

on: [ push ]

jobs:
  container-images:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner != 'project-openubl' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ "standalone", "enterprise" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Extract image name
        shell: bash
        run: |
          bash -c '
          flavor=${{ matrix.flavor }};
          image_name="searchpe";
          if [ $flavor != "standalone" ]; then
            image_name="$image_name-$flavor"
          fi
          echo $image_name;
          echo "##[set-output name=searchpe_image_name;]$(echo $image_name)"'
        id: extract_image_name
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build container image
        run: |
          mvn -U -B package --file pom.xml -DskipTests \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.name=${{ github.event.repository.name }}/${{ steps.extract_image_name.outputs.searchpe_image_name }} \
          -Dquarkus.container-image.tag=${{ steps.extract_branch.outputs.branch }} \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }} \
          -P native,ui,${{ matrix.flavor }}
