name: Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: { }

env:
  CI: true

jobs:
  linux-jvm-tests:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    name: Test real padron reducido
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Maven
        run: mvn test -Dtest=DataHelperTest -Dsearchpe.sunat.padronReducidoUrl=http://www2.sunat.gob.pe/padron_reducido_ruc.zip

  build-snapshot-container:
    needs: [ linux-jvm-tests ]
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Build container image
        run: |
          mvn -U -B package --file pom.xml -DskipTests \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.push=false \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.registry=quay.io \
          -Dquarkus.container-image.group=projectopenubl \
          -Dquarkus.container-image.name=searchpe \
          -Dquarkus.container-image.tag=latest \
          -P native,ui
      - name: Save container image
        run: docker save -o searchpe-container-image.tar quay.io/projectopenubl/searchpe:latest
      - name: Upload container image
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: searchpe-container-image.tar

  snapshots:
    needs: [ build-snapshot-container ]
    name: Snaphots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: Login to Ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
      - name: Load and config images
        run: |
          # Load images from .tar
          docker load -i artifacts/searchpe-container-image.tar
          
          # Tag images
          docker tag quay.io/projectopenubl/searchpe:latest quay.io/projectopenubl/searchpe:early-access      
          docker tag quay.io/projectopenubl/searchpe:latest ghcr.io/project-openubl/searchpe/searchpe:early-access
      - name: Push images to registry
        run: |
          docker push quay.io/projectopenubl/searchpe:early-access          
          docker push ghcr.io/project-openubl/searchpe/searchpe:early-access
