name: Snapshots

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs: { }

env:
  CI: true

jobs:
  linux-jvm-tests:
    name: Test real padron reducido
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Maven
        run: mvn test -Pstandalone -Dtest=DataHelperTest -Dsearchpe.sunat.padronReducidoUrl=http://www2.sunat.gob.pe/padron_reducido_ruc.zip

  snapshots:
    needs: [ linux-jvm-tests ]
    name: Snaphots
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [ "standalone", "enterprise" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: maven

      - name: Quay.io snapshot
        run: |
          mvn -U -B package --file pom.xml -DskipTests \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.registry=quay.io \
          -Dquarkus.container-image.group=projectopenubl \
          -Dquarkus.container-image.name=searchpe-${{ matrix.flavor }} \
          -Dquarkus.container-image.tag=early-access \
          -Dquarkus.container-image.username=${{ secrets.QUAYIO_USERNAME }} \
          -Dquarkus.container-image.password=${{ secrets.QUAYIO_PASSWORD }} \
          -P native,ui,${{ matrix.flavor }}
      - name: GitHub snapshot
        run: |
          mvn -U -B package --file pom.xml -DskipTests \
          -Dquarkus.native.container-build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.group=project-openubl \
          -Dquarkus.container-image.name=searchpe/searchpe-${{ matrix.flavor }} \
          -Dquarkus.container-image.tag=early-access \
          -Dquarkus.container-image.username=${{ github.actor }} \
          -Dquarkus.container-image.password=${{ secrets.GITHUB_TOKEN }} \
          -P native,ui,${{ matrix.flavor }}
