name: Verify SUNAT data

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  linux-jvm-tests:
    name: JVM Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Maven
        run: mvn test -Pstandalone -Dtest=DataHelperTest -Dsearchpe.sunat.padronReducidoUrl=http://www2.sunat.gob.pe/padron_reducido_ruc.zip
      - name: Prepare failure archive (if maven failed)
        if: failure()
        shell: bash
        run: find . -name '*-reports' -type d | tar -czvf test-reports.tgz -T -
      - name: Upload failure archive (if maven failed)
        uses: actions/upload-artifact@v2.3.0
        if: failure()
        with:
          name: test-reports-${{ matrix.flavor }}
          path: 'test-reports.tgz'
